apiVersion: apps/v1
kind: Deployment
metadata:
    name: queue
spec:
    selector:
        matchLabels:
            app: queue
    replicas: 1

    template: # Temlate for Pods
        metadata:
            labels:
              app: queue

        spec:
            containers:
            - name: webapp
              image: richardchesterwood/k8s-fleetman-queue:release1
